<?php

// Index/Signin
// User/Signup 		Admin
// User/Site 		Admin
// User/Signout
// User/account
// print -> status
// !print-> !status
// var_dump(unserialize('a:5:{s:106:"a:3:{s:0:"";s:13:"Index/Default";s:7:"<c:\w+>";s:11:"<c>/Default";s:17:"<c:\w+>/<a:\w+>/*";s:7:"<c>/<a>";}";a:2:{s:5:"value";s:690:"a:3:{i:0;a:7:{s:9:"urlSuffix";N;s:6:"params";a:0:{}s:7:"pattern";s:7:"/^\/$/u";s:12:"routePattern";N;s:10:"references";a:0:{}s:13:"defaultParams";a:0:{}s:5:"route";s:13:"Index/Default";}i:1;a:7:{s:9:"urlSuffix";N;s:6:"params";a:0:{}s:7:"pattern";s:17:"/^(?P<c>\w+)\/$/u";s:12:"routePattern";s:24:"/^(?P<c>\w+)\/Default$/u";s:10:"references";a:1:{s:1:"c";s:3:"<c>";}s:13:"defaultParams";a:0:{}s:5:"route";s:11:"<c>/Default";}i:2;a:7:{s:9:"urlSuffix";N;s:6:"params";a:0:{}s:7:"pattern";s:28:"/^(?P<c>\w+)\/(?P<a>\w+)\//u";s:12:"routePattern";s:27:"/^(?P<c>\w+)\/(?P<a>\w+)$/u";s:10:"references";a:2:{s:1:"c";s:3:"<c>";s:1:"a";s:3:"<a>";}s:13:"defaultParams";a:0:{}s:5:"route";s:7:"<c>/<a>";}}";s:6:"expire";i:0;}s:12:"SPPHPauthKey";a:2:{s:5:"value";s:32:"(|Zm_T~Oyc1`O/QoJ+owB>OF@|?9~ka|";s:6:"expire";i:0;}s:73:"a:2:{s:0:"";s:13:"Index/Default";s:17:"<c:\w+>/<a:\w+>/*";s:7:"<c>/<a>";}";a:2:{s:5:"value";s:452:"a:2:{i:0;a:7:{s:9:"urlSuffix";N;s:6:"params";a:0:{}s:7:"pattern";s:7:"/^\/$/u";s:12:"routePattern";N;s:10:"references";a:0:{}s:13:"defaultParams";a:0:{}s:5:"route";s:13:"Index/Default";}i:1;a:7:{s:9:"urlSuffix";N;s:6:"params";a:0:{}s:7:"pattern";s:28:"/^(?P<c>\w+)\/(?P<a>\w+)\//u";s:12:"routePattern";s:27:"/^(?P<c>\w+)\/(?P<a>\w+)$/u";s:10:"references";a:2:{s:1:"c";s:3:"<c>";s:1:"a";s:3:"<a>";}s:13:"defaultParams";a:0:{}s:5:"route";s:7:"<c>/<a>";}}";s:6:"expire";i:0;}s:106:"a:3:{s:0:"";s:13:"Index/Default";s:17:"<c:\w+>/<a:\w+>/*";s:7:"<c>/<a>";s:7:"<c:\w+>";s:11:"<c>/Default";}";a:2:{s:5:"value";s:690:"a:3:{i:0;a:7:{s:9:"urlSuffix";N;s:6:"params";a:0:{}s:7:"pattern";s:7:"/^\/$/u";s:12:"routePattern";N;s:10:"references";a:0:{}s:13:"defaultParams";a:0:{}s:5:"route";s:13:"Index/Default";}i:1;a:7:{s:9:"urlSuffix";N;s:6:"params";a:0:{}s:7:"pattern";s:28:"/^(?P<c>\w+)\/(?P<a>\w+)\//u";s:12:"routePattern";s:27:"/^(?P<c>\w+)\/(?P<a>\w+)$/u";s:10:"references";a:2:{s:1:"c";s:3:"<c>";s:1:"a";s:3:"<a>";}s:13:"defaultParams";a:0:{}s:5:"route";s:7:"<c>/<a>";}i:2;a:7:{s:9:"urlSuffix";N;s:6:"params";a:0:{}s:7:"pattern";s:17:"/^(?P<c>\w+)\/$/u";s:12:"routePattern";s:24:"/^(?P<c>\w+)\/Default$/u";s:10:"references";a:1:{s:1:"c";s:3:"<c>";}s:13:"defaultParams";a:0:{}s:5:"route";s:11:"<c>/Default";}}";s:6:"expire";i:0;}s:45:"a:1:{s:17:"<c:\w+>/<a:\w+>/*";s:7:"<c>/<a>";}";a:2:{s:5:"value";s:271:"a:1:{i:0;a:7:{s:9:"urlSuffix";N;s:6:"params";a:0:{}s:7:"pattern";s:28:"/^(?P<c>\w+)\/(?P<a>\w+)\//u";s:12:"routePattern";s:27:"/^(?P<c>\w+)\/(?P<a>\w+)$/u";s:10:"references";a:2:{s:1:"c";s:3:"<c>";s:1:"a";s:3:"<a>";}s:13:"defaultParams";a:0:{}s:5:"route";s:7:"<c>/<a>";}}";s:6:"expire";i:0;}}'));

var_dump(is_int(1));
